//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> Author { get; set; }
        public long ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
