//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleClaimsOnProject
    {
        public long Id { get; set; }
        public long RoleId { get; set; }
        public long ProjectId { get; set; }
        public Nullable<bool> HaveAcess { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
    }
}
