//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskControl.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Menu_Item {
            get {
                return ResourceManager.GetString("About_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account_Title {
            get {
                return ResourceManager.GetString("Account_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity_Tab {
            get {
                return ResourceManager.GetString("Activity_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity stream.
        /// </summary>
        public static string ActivityStream_Label_Dashboard {
            get {
                return ResourceManager.GetString("ActivityStream_Label_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new role.
        /// </summary>
        public static string AddNewRole_Button {
            get {
                return ResourceManager.GetString("AddNewRole_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аdd new user.
        /// </summary>
        public static string AddNewUser_Button {
            get {
                return ResourceManager.GetString("AddNewUser_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tasks.
        /// </summary>
        public static string AllTasks_Button {
            get {
                return ResourceManager.GetString("AllTasks_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string Assignee_Label {
            get {
                return ResourceManager.GetString("Assignee_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton_Label {
            get {
                return ResourceManager.GetString("BackButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList_Link {
            get {
                return ResourceManager.GetString("BackToList_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar_Menu_Item {
            get {
                return ResourceManager.GetString("Calendar_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ChangeSettings_Label {
            get {
                return ResourceManager.GetString("ChangeSettings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your language.
        /// </summary>
        public static string ChangeYourLanguage_Label {
            get {
                return ResourceManager.GetString("ChangeYourLanguage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangeYourPassword_Label {
            get {
                return ResourceManager.GetString("ChangeYourPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_Button {
            get {
                return ResourceManager.GetString("Close_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments_Tab {
            get {
                return ResourceManager.GetString("Comments_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete_ProgressBar_Label {
            get {
                return ResourceManager.GetString("Complete_ProgressBar_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Completed.
        /// </summary>
        public static string CompletedCount_Label {
            get {
                return ResourceManager.GetString("CompletedCount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword_Label {
            get {
                return ResourceManager.GetString("ConfirmPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_Menu_Item {
            get {
                return ResourceManager.GetString("Contact_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create_Button {
            get {
                return ResourceManager.GetString("Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string CreateNewProject_Button {
            get {
                return ResourceManager.GetString("CreateNewProject_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new role.
        /// </summary>
        public static string CreateNewRole_Title {
            get {
                return ResourceManager.GetString("CreateNewRole_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new task.
        /// </summary>
        public static string CreateNewTask_Button {
            get {
                return ResourceManager.GetString("CreateNewTask_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        public static string CreateNewUser_Label {
            get {
                return ResourceManager.GetString("CreateNewUser_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string DateCreated_Label {
            get {
                return ResourceManager.GetString("DateCreated_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Label {
            get {
                return ResourceManager.GetString("Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details_Label {
            get {
                return ResourceManager.GetString("Details_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done_PlanningBoard_Title {
            get {
                return ResourceManager.GetString("Done_PlanningBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DueDate.
        /// </summary>
        public static string DueDate_Label {
            get {
                return ResourceManager.GetString("DueDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_Link {
            get {
                return ResourceManager.GetString("Edit_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email_Label {
            get {
                return ResourceManager.GetString("Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to excel.
        /// </summary>
        public static string ExportToExcel_Button {
            get {
                return ResourceManager.GetString("ExportToExcel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find by name:.
        /// </summary>
        public static string FindByName_Label {
            get {
                return ResourceManager.GetString("FindByName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName_Label {
            get {
                return ResourceManager.GetString("FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        public static string Hello_Label {
            get {
                return ResourceManager.GetString("Hello_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Menu_Item {
            get {
                return ResourceManager.GetString("Home_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress_PlanningBoard_Title {
            get {
                return ResourceManager.GetString("InProgress_PlanningBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total In Progress.
        /// </summary>
        public static string InProgressCount_Label {
            get {
                return ResourceManager.GetString("InProgressCount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueType.
        /// </summary>
        public static string IssueType_Label {
            get {
                return ResourceManager.GetString("IssueType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName_Label {
            get {
                return ResourceManager.GetString("LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn_Button {
            get {
                return ResourceManager.GetString("LogIn_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Menu_Item {
            get {
                return ResourceManager.GetString("Login_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff_Label {
            get {
                return ResourceManager.GetString("LogOff_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tasks.
        /// </summary>
        public static string MyTasks_Button {
            get {
                return ResourceManager.GetString("MyTasks_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_Label {
            get {
                return ResourceManager.GetString("Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string NewProject_Label {
            get {
                return ResourceManager.GetString("NewProject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New role.
        /// </summary>
        public static string NewRole_Label {
            get {
                return ResourceManager.GetString("NewRole_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string NewTask_Title {
            get {
                return ResourceManager.GetString("NewTask_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview_Tab {
            get {
                return ResourceManager.GetString("Overview_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner_Label {
            get {
                return ResourceManager.GetString("Owner_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page_Label {
            get {
                return ResourceManager.GetString("Page_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Page_Of_Label {
            get {
                return ResourceManager.GetString("Page_Of_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password_Label {
            get {
                return ResourceManager.GetString("Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber_Label {
            get {
                return ResourceManager.GetString("PhoneNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning board.
        /// </summary>
        public static string PlanningBoard_Label_Dashboard {
            get {
                return ResourceManager.GetString("PlanningBoard_Label_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority_Label {
            get {
                return ResourceManager.GetString("Priority_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project access.
        /// </summary>
        public static string ProjectAccess_Title {
            get {
                return ResourceManager.GetString("ProjectAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects_Label {
            get {
                return ResourceManager.GetString("Projects_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects_Menu_Item {
            get {
                return ResourceManager.GetString("Projects_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Menu_Item {
            get {
                return ResourceManager.GetString("Register_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as new user.
        /// </summary>
        public static string RegisterNewUser_Link {
            get {
                return ResourceManager.GetString("RegisterNewUser_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        public static string Reporter_Label {
            get {
                return ResourceManager.GetString("Reporter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string RoleName_Label {
            get {
                return ResourceManager.GetString("RoleName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles_Menu_Item {
            get {
                return ResourceManager.GetString("Roles_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanged_Button {
            get {
                return ResourceManager.GetString("SaveChanged_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search!.
        /// </summary>
        public static string Search_Label {
            get {
                return ResourceManager.GetString("Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected project:.
        /// </summary>
        public static string SelectedProject_Label {
            get {
                return ResourceManager.GetString("SelectedProject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status_Label {
            get {
                return ResourceManager.GetString("Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks_Label {
            get {
                return ResourceManager.GetString("Tasks_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks_Menu_Item {
            get {
                return ResourceManager.GetString("Tasks_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title_Label {
            get {
                return ResourceManager.GetString("Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo.
        /// </summary>
        public static string ToDo_PlanningBoard_Title {
            get {
                return ResourceManager.GetString("ToDo_PlanningBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total ToDo.
        /// </summary>
        public static string ToDoCount_Label {
            get {
                return ResourceManager.GetString("ToDoCount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Progress.
        /// </summary>
        public static string TotalProgress_Label {
            get {
                return ResourceManager.GetString("TotalProgress_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User_Label {
            get {
                return ResourceManager.GetString("User_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username_Label {
            get {
                return ResourceManager.GetString("Username_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role.
        /// </summary>
        public static string UserRole_Label {
            get {
                return ResourceManager.GetString("UserRole_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users_Menu_Item {
            get {
                return ResourceManager.GetString("Users_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user to role.
        /// </summary>
        public static string АddUserToRole_Button {
            get {
                return ResourceManager.GetString("АddUserToRole_Button", resourceCulture);
            }
        }
    }
}
